language: objective-c
osx_image: xcode8

env:
  global:
    - WORKSPACE=HTTPDNS.xcworkspace
    - IOS_SCHEME=HTTPDNS_iOS
    - OSX_SCHEME=HTTPDNS_OSX
    - IOS_SDK=iphonesimulator10.0
    - OSX_SDK=macosx10.12
    - CONFIG="ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES"
  matrix:
    - SCHEME="$IOS_SCHEME"  SDK="$IOS_SDK" DESTINATION="OS=10.0,name=iPhone 7 Plus"
    - SCHEME="$IOS_SCHEME"  SDK="$IOS_SDK" DESTINATION="OS=9.0,name=iPhone 5"
    # - SCHEME="$OSX_SCHEME"  SDK="$OSX_SDK" DESTINATION="arch=x86_64"

script:
  - set -o pipefail
  - xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration "$CONFIG" test | xcpretty -c;
