language: objective-c
osx_image: xcode7.3

before_install:
  - brew update
  - brew outdated xctool || brew upgrade xctool

env:
  matrix:
    - SCHEME=HTTPDNS_iOS TEST_SDK=iphonesimulator8.0
    - SCHEME=HTTPDNS_iOS TEST_SDK=iphonesimulator9.0
    - SCHEME=HTTPDNS_iOS TEST_SDK=iphonesimulator
    - SCHEME=HTTPDNS_OSX TEST_SDK=macosx10.10
    - SCHEME=HTTPDNS_OSX TEST_SDK=macosx

script:
  xctool -scheme $SCHEME -sdk $TEST_SDK test
