language: objective-c

before_install:
  - brew update
  - brew outdated xctool || brew upgrade xctool

env:
  matrix:
    - SCHEME=HTTPDNS_iOS TEST_SDK=iphonesimulator
    - SCHEME=HTTPDNS_OSX TEST_SDK=macosx

script:
  xctool -scheme $SCHEME -sdk $TEST_SDK test
